# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(related_name='users', to='login_reg.User'),
        ),
    ]
